# Gradle properties - konfigurasi build system
org.gradle.jvmargs=-Xmx3072m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official

# Suppress warning for Compile SDK 35
android.suppressUnsupportedCompileSdk=35

# Kapt diganti KSP - lebih cepat 2x untuk code generation (Hilt, Room)
kapt.use.worker.api=false
